name: backbone
description: Lightweight, ECS-like package for Flame and Flutter
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.3.0
  benchmarking: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: